---
abstract: 'WebSocket version hixie-76 transaction'
author:
    - 'Denis Ibaev <dionys@cpan.org>'
build_requires:
    ExtUtils::MakeMaker: 0
configure_requires:
    ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
    url: http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
name: MojoX-Transaction-WebSocket76
no_index:
    directory:
        - t
requires:
    Mojolicious: 2.47
    Test::More: 0
    perl: 5.010001
resources:
    bugtracker: http://github.com/dionys/mojox-transaction-websocket76/issues
    license: http://dev.perl.org/licenses/
    repository: http://github.com/dionys/mojox-transaction-websocket76
version: 0.02
